#!/usr/bin/env python3
for x in range(99, 0, -1):
    print(x, "bottles of beer on the wall!\n", end=" ")
    print(x, "bottles of beer on the wall! \n",x, "bottles of beer!, \
        you take one down pass it around!", end=" ")
